// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnGnMz4Mq5Qp1ZJHw-BoJY23dfH9tHVxc',
    appId: '1:317436331871:web:7de02c46465ec14b7118ea',
    messagingSenderId: '317436331871',
    projectId: 'karteinkartenapp',
    authDomain: 'karteinkartenapp.firebaseapp.com',
    storageBucket: 'karteinkartenapp.appspot.com',
    measurementId: 'G-KFKRY6ECM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmd3SgpJooYuvrhlpAK42xdGPVX3YrroE',
    appId: '1:317436331871:android:0a6f8aa71858e1b87118ea',
    messagingSenderId: '317436331871',
    projectId: 'karteinkartenapp',
    storageBucket: 'karteinkartenapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF4JD9Xc5CJ41GIJ2U0_mKnonygIdYX1Y',
    appId: '1:317436331871:ios:e05cc6e1540e23c07118ea',
    messagingSenderId: '317436331871',
    projectId: 'karteinkartenapp',
    storageBucket: 'karteinkartenapp.appspot.com',
    androidClientId: '317436331871-nk2mter3duju675u3rgqnheb2uc0ckuh.apps.googleusercontent.com',
    iosClientId: '317436331871-vve8npocg6noorbsnrrbn29chte0450t.apps.googleusercontent.com',
    iosBundleId: 'com.example.karteikartenAppNew',
  );
}
